version: "3"
services:
  proxy:
    container_name: proxy
    image: caddy:2.1.1
    volumes:
      - ./client/:/usr/share/caddy/
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
    ports:
      - 4443:8080
  node:
    container_name: node
    image: node:alpine
    working_dir: /server
    command: ["npm", "run", "docker-dev"]
    expose:
      - 8443
    volumes:
      - ./server/:/server/
